### ISSUE TITLE
whitepaper / бумага проекта

### ISSUE THREAD

**Issue by kkrupovich** [chainflexspace/info#2]
Предположительно - описание целей проекта, путей их достижения, рисков

**Comment by kkrupovich** [comment]
@UspenskyDritry @mklinkov по поводу именно бумаги (не конституции) у меня вопрос - мы же бумагу пишем главным образом для фиксации subj - значит, нужно думать в направлении орг-структуры, экономики и предложений по реализации, правильно? Т.е. это больше моя задача, и основным исполнителем д.б. я?

**Comment by mklinkov** [comment]
@kkrupovich  я думаю, в любом случае обсуждение будет иметь место, но так как ты уже начинал прописывать идеологию тебе, стоит ее перенести сюда, с учетом результатов последних встреч.

**Comment by kkrupovich** [comment]
добавил страницу wiki для [бумаги](https://github.com/chainflexspace/info/wiki/Бумага)
https://github.com/chainflexspace/info/wiki/Бумага

**Comment by kkrupovich** [comment]
Решил все-таки зафиксировать текст бумаги в коммите в репозиторий info, файл [README.md](https://github.com/chainflexspace/info/commit/9b0e47e9a05dce68e283a7613669a172d7bda1af)

**Comment by kkrupovich** [comment]
Так как в целом концепция CHAINFLEX зафиксирована в первоначальной версии бумаги - текущий тикет закрываю. Изменения будем вносить в рабочем порядке путем добавления задач с доски проекта репозитория info
